apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sa-logic
spec:
  hosts:
    - sa-logic           # 1
  http:
  - route:
    - destination:
        host: sa-logic   # 2
        subset: v1       # 3
    mirror:              # 4
      host: sa-logic     
      subset: v2